apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chatbot-k1742466182841
  janus-idp.io/tekton: chatbot-k1742466182841
  backstage.io/kubernetes-id: chatbot-k1742466182841
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: chatbot-k1742466182841
resources:
  - application-dev.yaml
