apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-k1742466182841
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-k1742466182841
  name: chatbot-k1742466182841
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
