apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-k1742466182841
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-k1742466182841
  name: chatbot-k1742466182841
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: chatbot-k1742466182841
    weight: 100
  wildcardPolicy: None
