apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-k1742466182841
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-k1742466182841
  name: chatbot-k1742466182841
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-k1742466182841
